services:
  backend:
    image: "mc-backend"
    container_name: "mc-backend"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/storage:/storage
      - ./data/mcserver:/mcserver
    ports:
      - "${BE_PORT}:80"
    restart: unless-stopped
  
  
  # Minecraft server
  mcserver:
    image: itzg/minecraft-server:latest
    container_name: "mc-server"
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "${MC_PORT}:25565"
    environment:
      MODE: "${MC_MODE}"
      UID: 1001
      # MC config
      SEED: -8059940607247641339
      EULA: true
      VERSION: "1.20.1"
      TYPE: MOHIST # Forge/Bukkit hybrid
      MEMORY: "${MC_MEMORY}"
      USE_AIKAR_FLAGS: true
      DIFFICULTY: "${MC_DIFFICULTY}"
      SNOOPER_ENABLED: false
      MAX_BUILD_HEIGHT: 640 #experimental
      ONLINE_MODE: "${MC_ONLINE}"
      ALLOW_FLIGHT: "${MC_FLIGHT}"
      ENABLE_WHITELIST: false
    volumes:
      # attach the relative directory 'data' to the container's /data path
      # TODO: find out how this container chowns this volume
      - ./data/mcserver:/data
    restart: unless-stopped
    
