FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
RUN pwd
COPY ["./PashtetMcBackend/", "./PashtetMcBackend/"]
COPY ["./Common/", "./Common/"]
COPY ["./Launcher/", "./Launcher/"]
COPY ["./PashtetMc.sln", "./"]
RUN ls -al
WORKDIR "/src/PashtetMcBackend"
RUN dotnet publish "PashtetMcBackend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM base AS final
ARG USERNAME=appuser
ARG USER_UID=1001
ARG USER_GID=1000
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
WORKDIR /app
COPY --from=build /app/publish .
VOLUME /storage
VOLUME /mcserver

ENTRYPOINT ["dotnet", "PashtetMcBackend.dll"]
